### PR TITLE
chore: release 2024-04-03

### PR DESCRIPTION
**Pull request by alandtse**

### CODE REVIEW

**Comment by gkwok1** [comment]
@alandtse Any way to get this up on pypi.org and update https://github.com/alandtse/tesla upstream?

**Comment by alandtse** [comment]
It's already on pypi. Someone just needs to do the PR for Tesla.

**Comment by gkwok1** [comment]
showing 3.10.2 is latest on pypi.

https://pypi.org/project/teslajsonpy/
image

**Comment by alandtse** [comment]
@zabuldon your pypi account is being blocked for uploads to pypi. Can you please update that so the ci will function?

400 User 'Zabuldon' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.

**Comment by gkwok1** [comment]
@alandtse Thanks, I will submit a PR upstream once PyPi is updated

**Comment by sisachenko** [comment]
@alandtse fixed. Thank you.

**Comment by alandtse** [comment]
@gkwok1 I've manually published it. However, will still need @zabuldon to address so it can be handled automatically.

**Comment by alandtse** [comment]
@zabuldon See https://github.com/zabuldon/teslajsonpy/pull/467#issuecomment-2052428952. Basically pypi needs verified email addresses.

**Comment by zabuldon** [comment]
I already did that.

**Comment by alandtse** [comment]
Ahh ok. Well we'll see what happens the next time the publish ci runs and I'll ping you if there's an issue.

**Comment by zabuldon** [comment]
Sure, thanks

**Pull request merged**
