### PR TITLE
Add Heating Steering Wheel Support & Move Heated Seats to SELECT

### PR DESCRIPTION
**Pull request by megabytemb**
Hello, 

I don't usually add to Open Source, so please go easy :)

As a pre-cursor to adding heated Steering Wheel support into Home Assistant, I've added the steering wheel support into this library.

Also, Heated seats, although in the library, was never implemented in Home Assistant.
Home Assistant now supports "Select" entities, which works really nicely for heated seats.

If you approve this Pull request, i'll then do another for Home Assistant directly to add this functionality.

Added Tests and confirmed linting as required.

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks for doing this. Sorry I didn't even realize you had submitted this as my notifications are off here.

**Comment by alandtse** [comment]
Would this close #192 too?

**Comment by megabytemb** [comment]
I wasn't aware of that conversation going on. 

I believe it does. Select is a new entity type in Home Assistant, and IMO, fits the use case of a seat warmer perfectly.

However, Perhaps we should look at how to handle "errors" when the climate control isn't turned on. At the moment, it just silently fails.
I think just having the feature in home assistant, and appropriate documentation around it is good enough, but always open for discussion.

**Comment by alandtse** [comment]
Thanks. We currently are silent for all errors unless it's an underlying library exception. But we probably could throw an exception. I'm ok with this for now and will add it to dev. Please consider adding the exception throwing in another pr.

**Pull request merged**
