### PR TITLE
fix: update powerwall endpoints

### PR DESCRIPTION
**Pull request by gkwok1**

### CODE REVIEW

**Comment by jaymunro** [comment]
How about the logger changes from line 683 in controller.py?
https://github.com/zabuldon/teslajsonpy/compare/dev...jaymunro:teslajsonpy:patch-1#

**Comment by gkwok1** [comment]
> How about the logger changes from line 683 in controller.py? [dev...jaymunro:teslajsonpy:patch-1](https://github.com/zabuldon/teslajsonpy/compare/dev...jaymunro:teslajsonpy:patch-1)

The changes are on line 718 - 726 in my controller.py file.

**Comment by jaymunro** [comment]
Strike, that. I see the logger is updated too. Just a few lines down. 
Nice work.

**Comment by alandtse** [comment]
This breaks a lot of tests due to the name changes. Please address. You can ignore the tests related to the updater since that's a bad test.

**Comment by jaymunro** [comment]
@gkwok1 Do you need someone to help with the tests, or are you all good?

**Comment by gkwok1** [comment]
@jaymunro @alandtse just added you as a collaborator, please feel free to edit the tests since I am still very new to this. Thanks.

**Comment by gkwok1** [comment]
@alandtse I think I fixed everything in test.

**Comment by jaymunro** [comment]
Looking good. Just need someone with write access to approve the PR. Many people waiting for this, some even losing money due to power usage automations not working.

**Comment by alandtse** [comment]
Tests still failing.

**Comment by gkwok1** [comment]
@alandtse All checks have passed now. Thanks.

**Review by alandtse — APPROVED** [review]

**Comment by alandtse** [comment]
Great, thanks for your hard work on this.

**Pull request merged**
