### PR TITLE
Polling policy

### PR DESCRIPTION
**Pull request by Olen**
See #166 

This PR adds a new flag; "polling_policy" to allow for some granularity on the polling.
If "polling_policy" is set to "always", the controller will keep polling every "update_interval" except when the car is driving (when DRIVING_INTERVAL is used instead).
Be aware that this will probably never allow the car to sleep, so it might drain the battery more than necessary.

If "polling_policy" us set to "connected", the poller will run normally as long as the car is connected to a charger.  This will increase vampire drain slightly, but only while connected to a charger, so it should not cause a problem while parked without a charger connected.

The normal polling policy will still be default, and only poll while the car is driving, charging, or while sentry mode or climate is on.

### CODE REVIEW

**Comment by alandtse** [comment]
The code looks fine. Do you mind adding tests just for this new parameter? I realize we don't have a test yet for the controller but we've been trying to improve on that.

**Comment by Olen** [comment]
Hi, and thanks for the review.
I am not sure exactly where I should add that test.
It seems like all the tests in test/home-assitant/* are just running `_controller = Controller(None)` so they don't test any parameters at all, so I don't really know where to start...

To actually validate that it works as intended would be pretty complex, and I don't know the code well enough to write a usable test, I am afraid.
You would pobably need to first set up a default controller, force charge_state to "Charging", check the reslt from _calculate_next_interval.
Then force charge_state to "Complete" and then check that result from _calculate_next_interval
Then force charge_state to "Disconnected" and then check that result from _calculate_next_interval

And then do the same 3 tests again for polling_policy "connected" and "always".

**Comment by alandtse** [comment]
I can probably set up a framework file with one example if you'd be willing to do the rest. All you have to do is mock the API state and then test the `_calculate_next_interval` function to see which time it is returning.

**Comment by Olen** [comment]
Thanks. Please set up an example, and I will do the rest.

**Comment by Olen** [comment]
Hm,
I thought I could just add some more tests here:
https://github.com/zabuldon/teslajsonpy/blob/dev/tests/unit_tests/homeassistant/test_charger_connection_sensor.py

But `_calculate_next_interval()` is a nested function inside `async def update()`, and apparently nested functions can't really be tested very easily...

**Comment by alandtse** [comment]
It should probably be in test_controller.py (not created yet) and you're right you can't test inner functions.  We'll have to mock the API responses (like the other test functions) to get it into the different states.

**Comment by Olen** [comment]
Yeah. Getting it into the states is one thing. But I am trying to wrap my head around how to test the "next interval", since it is only used in one location, and only to check if it should append a task.

An idea I am playing with is to monitor some arbitrary value (like "battery_level")
- Set charging state to Charging
- run update()
- Verify that battery_level is the default value (64)
- set battery_level = 10 somehow
- Run "update()
- Verfy that it is still 64 (should not have updated the value, since it is less than 1 minute since the last update)
- Force _last_update_time[vin] to be more than one minute ago  
- Run "update()
- Verify that battery_level is now the mocked value (10)


And then do the same for different states and last_update_time to validate if it actually runs an update or not.

**Comment by alandtse** [comment]
Thinking about it more, let's break it out as a helper function and write a test against it.

**Comment by alandtse** [comment]
> When you say a helper-function is it as easy as moving the `def _calculate_next_interval` up a level, and out of the update() function?

Yup, that's all I meant.

**Comment by Olen** [comment]
So many private variables in the controller...
Had to add quite a few other functions to be able to test all the settings.  But I believe this should work now.

**Pull request merged**
