### PR TITLE
feat: add sentry mode switch to fix issue #43

### PR DESCRIPTION
**Pull request by hobbe**
Add a switch to enable/disable sentry mode for Tesla vehicle in Home Assistant. This should fix issue #43.

### CODE REVIEW

**Comment by tobbensoft** [comment]
Nice :)

Doesn't this need a HA switch update to work?  Is that available to try?

**Comment by hobbe** [comment]
@tobbensoft, this will need an update to the [Tesla component in HA](https://github.com/home-assistant/core/tree/dev/homeassistant/components/tesla), including a teslajsonpy library update and a new switch.

**Comment by alandtse** [comment]
Oooh awesome. I'll merge it in. I'll be doing a dependency bump in HA but leave it to you to add the component in HA.

**Comment by alandtse** [comment]
@hobbe Thanks again! 
I didn't look at the code too closely before merging as I was super excited to see someone helping, but can you submit a PR to remove the checks for the current sentry state in case the known state isn't accurate? It's the reason for my latest PR #64 and prompted by the bug [here](https://github.com/home-assistant/core/issues/32801#issuecomment-599183693).

**Comment by hobbe** [comment]
> @hobbe Thanks again!
> I didn't look at the code too closely before merging as I was super excited to see someone helping, but can you submit a PR to remove the checks for the current sentry state in case the known state isn't accurate? It's the reason for my latest PR #64 and prompted by the bug [here](https://github.com/home-assistant/core/issues/32801#issuecomment-599183693).

@alandtse, PR #66 submitted 👍

**Pull request merged**
