### PR TITLE
Fixes for initialization of heated seats

### PR DESCRIPTION
**Pull request by Trupal00p**
Fixes for #186

### CODE REVIEW

**Comment by alandtse** [comment]
Can you please add a test for the case where it broke before where the data isn't initialized yet?

**Comment by alandtse** [comment]
We're close to pushing a new release to address the login errors. Any chance to get that test in place so I can merge this too?

**Comment by Trupal00p** [comment]
Sorry for the delayed reply.  I think the changes I made on 47e5f23 in test_heated_seat.py (line 33) address this.  It's the same approach used by the initialization tests for the other components.

**Comment by alandtse** [comment]
I mean do we have a test in place to make sure we don't get the exception on startup #186 ? In theory after your fixes, you won't get the exception but this is to prevent a regression in the future.

**Comment by alandtse** [comment]
Ok. Thanks!

**Pull request merged**
