### PR TITLE
Update repo documents and complete linting

### LINKED ISSUE #22: Truncate VIN number for uniq_name
Given many HA configs are publicly hosted, posting the full VIN is probably not a good privacy setting.

### PR DESCRIPTION
**Pull request by alandtse**
@zabuldon This is a fairly massive set of changes so want to make sure you approve it specifically. 
- Add VIN truncation and display name per agreement in #23 (fixes #22). This is a breaking HA change as entity_ids will change.  I can handle the PR in HA.
- Clarified functionality of ChargerConnectionSensor to reflect connected cable fixes (#9). Charger switch will reflect whether the cable is actively charging.
- Rearchitected setup.py to use version from [here](https://github.com/kennethreitz/setup.py) that adds version importing and other features.
- Fleshed out the README and other documentation (e.g., AUTHORS). Please note I changed the README to markdown.
- Added Makefile based tests and publishing using pyenv.  See README for steps.
- Resolved all flake8, pylint, and pydocs errors.   **Please note**, this required a few name changes to snake_case instead of camelcase which means case insensitive .git configs may need to pull in the repo fresh instead of a rebase or merge. I ran into this a few times doing the rebase/merge issues on macOS. Once merged in, I'll plan to blow away my local repo to avoid that problem.

### CODE REVIEW

**Comment by alandtse** [comment]
@zabuldon I'll plan to merge this in a week unless you have an objection to the structural change. I've been gated by this since my dev environment would be very different if we don't have this in.

**Comment by zabuldon** [comment]
Basically I don't have any concerns about the commit, but please add requirements.txt as you did for pipfile.

**Comment by zabuldon** [comment]
Also, as I remember, you wanted to change a license. Feel free to do it in this big rock change

**Comment by alandtse** [comment]
> please add requirements.txt as you did for pipfile.

The [purpose of using pipenv](https://realpython.com/pipenv-guide/) is so we don't have to include a requirements.txt. Do you still want it?

**Comment by zabuldon** [comment]
I know why we are using pipenv, but some developers doesn't like it. It is good practice to keep this file. Anyway it is up to you to create it or not, I just recommend that.

**Comment by alandtse** [comment]
Ok, let's try without it until we get other devs contributing who complain that we're missing it. I'd like to avoid having to keep both `requirements.txt` and `pipfile` synced.

**Pull request merged**
