### PR TITLE
feat: add valet mode command and property

### PR DESCRIPTION
**Pull request by InTheDaylight14**
I guess my formatted decided to make some changes. coverage/lint/typing went okay, Not sure what happened there.

### CODE REVIEW

**Comment by alandtse** [comment]
Are you using black? The black config should be there if you're using poetry. It could be you have a system level black with different settings than the project.

**Comment by InTheDaylight14** [comment]
Yeah, I think I have black at system level (VSCode extension) and I'm using poetry.

**Comment by InTheDaylight14** [comment]
> Yeah, I think I have black at system level (VSCode extension) and I'm using poetry.

Hmm, disabling that extension and the going poetry lint did not change anything.

**Comment by alandtse** [comment]
Make sure vscode is using the poetry environment.

**Pull request merged**
