### PR TITLE
Add option for filtering cars by VIN

### LINKED ISSUE #84: Filter cars returned to Home Assistant
Give the choice to limit the resulting components to a subset of the cars connected to the account.
This is very useful in case the user has access to more than one car but does not want to control all of them in Home Assistant. 

This could be achieved by passing an optional list of VINs to connect(...)

### PR DESCRIPTION
**Pull request by alexpilotti**
Closes #84

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Does this pass the `make lint`? I'm not sure it'll accept `VINs` given the capitalization. Let's change it to `filtered_vins` so it's clear.

I assume you've also confirmed that it's not trying to update those vehicles too right?

**Comment by alexpilotti** [comment]
@alandtse done, thanks! Here's the successful make lint output: http://paste.openstack.org/show/795249/

**Comment by alexpilotti** [comment]
> I assume you've also confirmed that it's not trying to update those vehicles too right?

Yes, only the entities belonging to the filtered vehicles are meant to be visible in Home Assistant

**Comment by alandtse** [comment]
Thanks. I'll do a master build now so you can get a version # you can use to update HA.

**Comment by alexpilotti** [comment]
Perfect thanks! I’ll get the HA patch ready in the meantime.

**Pull request merged**
