### PR TITLE
Switch to json request

### PR DESCRIPTION
**Pull request by haoboji**

### CODE REVIEW

**Comment by haoboji** [comment]
resolves alandtse/tesla#231

**Comment by haoboji** [comment]
resolves #320

**Comment by haoboji** [comment]
resolves timdorr/tesla-api#594

**Comment by alandtse** [comment]
Thanks. Did you confirm this doesn't break something like standard login logout?

**Comment by alandtse** [comment]
You should only mark it as closing issues on relevant libraries.  Timdorr's repo is a documentation library so merging this in won't "close" that issue for them.

May also close #316

**Comment by haoboji** [comment]
Hi @alandtse , I've removed the links to other repos. I verified the change in the context of Home Assistant including the situation where access token is refreshed. By looking through the code I did not find anything that may break. It seems to me that the change does not affect login/logout, which invokes `self.websession.get/post` directly instead of the custom ones `self.get/post`.

**Pull request merged**
