### PR TITLE
add heated seats switch

### PR DESCRIPTION
**Pull request by Trupal00p**
I added an abstraction and tests to control the heated seats.  Wanted to set up an automation to turn these on when the outside temp is low.

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks! Please fix the lint errors.

**Comment by Trupal00p** [comment]
I've fixed the linter errors, but the checks still seem to be failing... not sure if it's something on my end?

**Comment by alandtse** [comment]
Thanks I'll take a look. I assume local tests are passing?

**Comment by Trupal00p** [comment]
Yep tests and linter checks are all passing locally.

**Comment by alandtse** [comment]
Did you run black. The linter is complaining about extra spaces.

**Comment by alandtse** [comment]
Also, you'll need to expose the switch to the controller for it to be picked up in HA.
https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/controller.py#L529

**Comment by Trupal00p** [comment]
ok i *think* I've got it this time 😋

**Comment by Trupal00p** [comment]
I think this ultimately should be set with the properties and methods of a [fan ](https://developers.home-assistant.io/docs/core/entity/fan)(for low, med, high presets) but it's not clear to me if that is to be done in this lib or on the HA component side?

**Comment by alandtse** [comment]
Thanks look good. The choice of representation for HA is up to you. This [list](https://developers.home-assistant.io/docs/core/entity/climate) is what is built in, but perhaps it's time to open a new set of options for cars. This might be best as an architecture [discussion](https://github.com/home-assistant/architecture).  Tesla isn't the car integration so perhaps we can look at what others are doing.

I'll merge this into the new main branch for a release. Please note I've only tested the latest versions using this new oauth login [method](https://github.com/home-assistant/core/pull/46558). You may be able to get it to login using the official dev branch or you may need to do some tweaks. I'd suggest testing dev against the latest version of teslajsonpy and confirming it can actually log in before doing any work on your HA component.

**Comment by alandtse** [comment]
@Trupal00p 

I'm getting this error in a live system. Can you please check and provide a fix? Please note there will be vehicles that may not have seat heaters.

```
  File "/workspaces/home-assistant/homeassistant/components/tesla/config_flow.py", line 229, in validate_input
    config = await controller.connect(
  File "/workspaces/home-assistant/config/teslajsonpy/controller.py", line 316, in connect
    self._add_components(car)
  File "/workspaces/home-assistant/config/teslajsonpy/controller.py", line 549, in _add_components
    self.__components.append(HeatedSeatSwitch(car, self, 'left'))
  File "/workspaces/home-assistant/config/teslajsonpy/homeassistant/heated_seats.py", line 47, in __init__
    self.__seat_heat_level = data['climate_state'][f'seat_heater_{seat_name}']
KeyError: 'climate_state'
```

I'll spawn a new issue with this comment so please respond there.

**Pull request merged**
