### PR TITLE
feat: add trunk and frunk management

### PR DESCRIPTION
**Pull request by hobbe**
In order to fix issue #50, this PR adds:

- 🔒 lock for rear trunk (lock/unlock)
- 🔒 lock for front trunk (frunk) (lock/unlock)

### CODE REVIEW

**Comment by alandtse** [comment]
Aren't the sensors redundant of the switch?

**Comment by hobbe** [comment]
Yeah. I needed to know if the trunk was open. Then I thought a switch would also enable opening/ closing it.
But in the end, I think a lock would be more appropriate. 
I will do some cleaning.

**Comment by hobbe** [comment]
This PR adds trunk/frunk locks.
No changes are necessary in HA, the locks are added out-of-the-box :+1:

**Comment by alandtse** [comment]
Once this is merged in you will need to do a HA PR to do the version bump and explain the new features it brings in. Also you'll need to do the documentation update.

**Pull request merged**
