### PR TITLE
Deep copy mock data to avoid cross-test pollution

### LINKED ISSUE #121: Test failure
One test is failing. This came up during the review for the NixOS package.

```bash
Executing pytestCheckPhase
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/source, configfile: tox.ini
collected 151 items                                                            

tests/test_tesla_exception.py ...............                            [  9%]
[...]
tests/unit_tests/homeassistant/test_vehicle_device.py ..Fssss            [100%]

=================================== FAILURES ===================================
_____________________________ test_values_on_init ______________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7ffff5e3e700>

    def test_values_on_init(monkeypatch):
        """Test values after initialization."""

        _mock = TeslaMock(monkeypatch)
        _controller = Controller(None)

        _data = _mock.data_request_vehicle()
        _device = VehicleDevice(_data, _controller)

        assert _device is not None

        assert _device.car_name() is not None
        assert _device.car_name() == "Nikola 2.0"

        assert _device.car_type is not None
        assert _device.car_type == "Model S"

        assert _device.car_version is not None
        assert _device.car_version == ""

        assert _device.id() is not None
        assert _device.id() == 12345678901234567

        assert _device.sentry_mode_available is not None
>       assert _device.sentry_mode_available
E       assert False
E        +  where False = <teslajsonpy.homeassistant.vehicle.VehicleDevice object at 0x7ffff5e3eb20>.sentry_mode_available

tests/unit_tests/homeassistant/test_vehicle_device.py:59: AssertionError
=========================== short test summary info ============================
FAILED tests/unit_tests/homeassistant/test_vehicle_device.py::test_values_on_init
=================== 1 failed, 60 passed, 90 skipped in 0.83s ===================
```

It would be nice if you could have a look. Thanks.

### PR DESCRIPTION
**Pull request by graham33**
Closes #121

### CODE REVIEW

**Comment by graham33** [comment]
This may not be the cleanest approach, but it fixes the test for me.

**Comment by alandtse** [comment]
Thanks for putting this together. However, the ci test is failing now. Any thoughts on the cause?

**Comment by graham33** [comment]
I wasn't running the asyncio tests in my environment, so didn't see that the data in TeslaMock needs to by shared for the lifetime of the test (mine returned a new deep copy on every function call).  I've rewritten it and the tests now pass, but it's a more invasive change that could be done a few different ways. I've tried to keep the change minimal vs a big refactoring.

**Comment by alandtse** [comment]
Great thanks!

**Pull request merged**
