### PR TITLE
feat: add pytest and coverage

### PR DESCRIPTION
**Pull request by hobbe**
Enable pytest and coverage framework to address issue #26.

Add a mock to simulate Tesla servers in unit tests.
Add tests for sentry mode, GPS, odometer, battery, range, charger connection, online, parking.

Fix initialization of sentry_mode_available in VehicleDevice and sentry_mode in SentryModeSwitch.

### CODE REVIEW

**Comment by hobbe** [comment]
Hi @zabuldon, @alandtse
I have added quite a few tests using pytest (with plugins asyncio and cov). I am not an expert and hopefully, I am not going in the wrong direction.
Please comment and advise if necessary, thanks!

**Comment by alandtse** [comment]
Thanks this is awesome. No negative judgment from me as the test suite closes something I haven't done for years now despite the issue #26 mainly cause I also am just learning.

There are a few warnings though. Have you taken a look to try to reduce them? Not saying it has to be done if you're not sure how--particularly given how much better it is with this, but would be nice to have those resolved.
```bash
========================================================= warnings summary ==========================================================
/Users/alandtse/.local/share/virtualenvs/teslajsonpy-JT0bMHGZ/lib/python3.7/site-packages/pytest_asyncio/plugin.py:39: 47 tests with warnings
  /Users/alandtse/.local/share/virtualenvs/teslajsonpy-JT0bMHGZ/lib/python3.7/site-packages/pytest_asyncio/plugin.py:39: PytestDeprecationWarning: direct construction of Function has been deprecated, please use Function.from_parent
    item = pytest.Function(name, parent=collector)

/Users/alandtse/.local/share/virtualenvs/teslajsonpy-JT0bMHGZ/lib/python3.7/site-packages/pytest_asyncio/plugin.py:45: 47 tests with warnings
  /Users/alandtse/.local/share/virtualenvs/teslajsonpy-JT0bMHGZ/lib/python3.7/site-packages/pytest_asyncio/plugin.py:45: PytestDeprecationWarning: direct construction of Function has been deprecated, please use Function.from_parent
    item = pytest.Function(name, parent=collector)  # To reload keywords.

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================== 77 passed, 94 warnings in 0.54s ==================================================
```

**Comment by hobbe** [comment]
> There are a few warnings though. Have you taken a look to try to reduce them? Not saying it has to be done if you're not sure how--particularly given how much better it is with this, but would be nice to have those resolved.

All the warnings are linked to pytest-asyncio. See https://github.com/pytest-dev/pytest-asyncio/issues/141.

Downgrading to pytest<5.4.1 (5.3.5) removes all warnings 👍

**Comment by alandtse** [comment]
It's an upcoming deprecation warning. I don't think pinning to an older version to avoid the warning is necessarily the way to solve it. ;) 

Let me know when you think you've finished your pushes.

**Comment by hobbe** [comment]
> It's an upcoming deprecation warning. I don't think pinning to an older version to avoid the warning is necessarily the way to solve it. ;)

Right! I am not downgrading pytest, just confirming that the warnings are not linked to teslajsonpy.

**Comment by hobbe** [comment]
> Let me know when you think you've finished your pushes.

Coverage is 69% total, 100% for device and sensors.
Only Controller and Connection remain. But I am not sure how to mock these.

If you are satisfied with the current status, please merge. We can see how to provide unit tests for Connection and Controller later.

**Comment by alandtse** [comment]
Thanks for all your help. Merging it shortly. Mocking those are probably just mocking the return values from the Tesla servers based off data we've seen before.

**Pull request merged**
